#!/usr/bin/env python3
"""Ask Gemini (Vertex AI, your gcloud login) to compare a real recording with generated renders of the same text.

    python render/gemini_compare.py --text bulletin/klar_text.txt --real bulletin/klar_real.wav \
        --generated bulletin/klar_generated_klarvoice.wav bulletin/klar_generated_puck.wav [--model gemini-2.5-pro]

Needs `gcloud auth print-access-token` to work and the Vertex AI API enabled on the active project. Audio is sent inline
(a few hundred tokens per 20 s clip). The reply is printed and written next to --real as gemini_report.md.
Evidence only, like Whisper: a second opinion on pronunciation, not a verdict."""
import argparse, base64, json, subprocess, sys, urllib.request
from pathlib import Path

PROMPT = """You are a native speaker of Hasidic (Heimish) Yiddish as spoken in Brooklyn and Monsey, and a careful phonetician.
Attached are audio clips of the SAME Yiddish text. Clip 1 is a real human narrator from the Yiddish 24 news service.
The other clips are generated by a text-to-speech model that is being tuned to pronounce Heimish Yiddish correctly.

The text (as transcribed):
{text}

For EACH generated clip, compared with the real narrator:
1. List every word that is pronounced differently from the narrator or wrongly for Heimish Yiddish. For each, give the word
   in Hebrew letters, how the narrator says it, how the generated clip says it, and whether the difference matters (dialect
   vowel, wrong consonant, wrong stress, garbled, skipped).
2. Rate pronunciation accuracy 0-10 (10 = indistinguishable from the narrator in the words spoken).
3. Rate naturalness / prosody 0-10 and note pace vs the narrator.
4. Note anything skipped, repeated, or garbled.
Be specific and concise. Answer in English; keep the Yiddish words in Hebrew letters."""


def part(path):
    return {"inlineData": {"mimeType": "audio/wav", "data": base64.b64encode(Path(path).read_bytes()).decode()}}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--text", required=True); ap.add_argument("--real", required=True); ap.add_argument("--generated", nargs="+", required=True)
    ap.add_argument("--model", default="gemini-2.5-pro"); ap.add_argument("--location", default="us-central1")
    a = ap.parse_args()
    token = subprocess.check_output(["gcloud", "auth", "print-access-token"], text=True).strip()
    project = subprocess.check_output(["gcloud", "config", "get-value", "project"], text=True).strip()
    text = Path(a.text).read_text(encoding="utf-8").strip()
    parts = [{"text": PROMPT.format(text=text)}, {"text": "Clip 1 (REAL narrator):"}, part(a.real)]
    for k, g in enumerate(a.generated, 2):
        parts += [{"text": f"Clip {k} (GENERATED, file {Path(g).name}):"}, part(g)]
    body = json.dumps({"contents": [{"role": "user", "parts": parts}], "generationConfig": {"temperature": 0.2}}).encode()
    url = f"https://{a.location}-aiplatform.googleapis.com/v1/projects/{project}/locations/{a.location}/publishers/google/models/{a.model}:generateContent"
    req = urllib.request.Request(url, data=body, headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=300) as r: resp = json.load(r)
    except urllib.error.HTTPError as e:
        sys.exit(f"HTTP {e.code}: {e.read()[:800].decode(errors='replace')}")
    out = "".join(p.get("text", "") for p in resp["candidates"][0]["content"]["parts"])
    usage = resp.get("usageMetadata", {})
    report = Path(a.real).with_name("gemini_report.md")
    report.write_text(f"# Gemini comparison ({a.model})\n\nText:\n\n{text}\n\nReal: {a.real}\nGenerated: {', '.join(a.generated)}\n\n{out}\n\n_tokens: {usage.get('totalTokenCount')}_\n", encoding="utf-8")
    print(out); print(f"\n[tokens {usage.get('totalTokenCount')}; written {report}]")


if __name__ == "__main__":
    main()
